import React, { useState } from 'react';

export default function ReportsTab({ reports, researchId, onRefresh }) {
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState({ title: '', type: '', format: 'PDF', generatedBy: '', content: '', status: 'Generated' });

  const handleSubmit = async (e) => {
    e.preventDefault();
    await fetch(`${API_URL}/api/reports`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ...formData, researchId })
    });
    setShowForm(false);
    setFormData({ title: '', type: '', format: 'PDF', generatedBy: '', content: '', status: 'Generated' });
    onRefresh();
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px', alignItems: 'center' }}>
        <h3>Research Reports</h3>
        <button className="btn btn-primary" onClick={() => setShowForm(true)}>+ Generate Report</button>
      </div>

      {showForm && (
        <div className="glass-panel" style={{ padding: '24px', marginBottom: '24px' }}>
          <h4 style={{ marginBottom: '16px' }}>New Report</h4>
          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <input style={{ padding: '8px', borderRadius: '4px', border: '1px solid var(--border-light)' }}
                placeholder="Report Title" required value={formData.title}
                onChange={e => setFormData({ ...formData, title: e.target.value })} />
              <select style={{ padding: '8px', borderRadius: '4px', border: '1px solid var(--border-light)' }}
                value={formData.format} onChange={e => setFormData({ ...formData, format: e.target.value })}>
                <option>PDF</option><option>DOCX</option><option>XLSX</option><option>HTML</option>
              </select>
              <input style={{ padding: '8px', borderRadius: '4px', border: '1px solid var(--border-light)' }}
                placeholder="Type (e.g. Progress, Financial)" value={formData.type}
                onChange={e => setFormData({ ...formData, type: e.target.value })} />
              <input style={{ padding: '8px', borderRadius: '4px', border: '1px solid var(--border-light)' }}
                placeholder="Generated By" value={formData.generatedBy}
                onChange={e => setFormData({ ...formData, generatedBy: e.target.value })} />
            </div>
            <textarea style={{ padding: '8px', borderRadius: '4px', border: '1px solid var(--border-light)', minHeight: '80px' }}
              placeholder="Report Content / Notes" value={formData.content}
              onChange={e => setFormData({ ...formData, content: e.target.value })} />
            <div style={{ display: 'flex', gap: '12px', justifyContent: 'flex-end' }}>
              <button type="button" className="btn btn-secondary" onClick={() => setShowForm(false)}>Cancel</button>
              <button type="submit" className="btn btn-primary">Generate</button>
            </div>
          </form>
        </div>
      )}

      <div className="glass-panel" style={{ padding: '24px' }}>
        {reports.length === 0 ? (
          <p style={{ color: 'var(--text-secondary)' }}>No reports generated.</p>
        ) : (
          reports.map(r => (
            <div key={r.id} style={{ borderBottom: '1px solid var(--border-light)', paddingBottom: '16px', marginBottom: '16px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div style={{ flex: 1 }}>
                  <h4 style={{ margin: '0 0 4px 0' }}>{r.title}</h4>
                  <div style={{ display: 'flex', gap: '12px', marginTop: '8px', flexWrap: 'wrap', fontSize: '13px', color: 'var(--text-secondary)' }}>
                    <span>Type: {r.type || '—'}</span>
                    <span>Format: {r.format}</span>
                    <span>By: {r.generatedBy || '—'}</span>
                    <span style={{ padding: '2px 8px', background: '#e8f0fe', borderRadius: '4px' }}>{r.status}</span>
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}