@echo off
cd /d "%~dp0"
set STATCOLLECT_PORT=:8080
set STATCOLLECT_DATA_DIR=./data
set STATCOLLECT_DB_HOST=localhost
set STATCOLLECT_DB_USER=statcollect
set STATCOLLECT_DB_PASSWORD=Statgate
set STATCOLLECT_DB_NAME=statcollect
set STATCOLLECT_API_KEY=changeme
set STATCOLLECT_ADMIN_KEYS=changeme
set STATCOLLECT_USE_S3=false

REM ── StatGate Platform Integration ──
set STATGATE_REGISTRY_JWT_SECRET=REDACTED_PLACEHOLDER
set STATGATE_INTERNAL_API_KEY=REDACTED_PLACEHOLDER
set STATGATE_TENANT_ID=default
set STATCOLLECT_ENABLE_EVENTS=true
set STATCOLLECT_ENABLE_STATCHAT=true
set REDIS_ADDR=localhost:6379
set STATCHAT_API_URL=http://localhost:4000
set STATGATE_REGISTRY_API_URL=http://localhost:9090/api

statcollect.exe