import { User, UserRole, Application, AppStatus, AppCategory } from '@typings/index';

// Mock user data for development
export const MOCK_USER: User = {
  id: 'user-001',
  name: 'John Mwase',
  email: 'john.mwase@statgate.ug',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
  role: UserRole.ADMIN,
  permissions: ['view:all', 'manage:apps', 'admin:access'],
  department: 'Data Analytics',
  lastLogin: new Date(Date.now() - 3600000),
};

// Real applications hosted by the StatGate platform
export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-analytics',
    name: 'StatGate Analytics',
    description: 'Analytical workspace with dataset catalog, notebooks, semantic registry, and executive decision support',
    icon: '📊',
    url: 'http://localhost:5000',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:5000/health',
    documentation: 'http://localhost:5000/',
    tags: ['analytics', 'dashboard', 'notebook'],
  },
  {
    id: 'app-registry',
    name: 'Field Operations Registry',
    description: 'Facility registry with master facility list, organization units, and request workflows',
    icon: '🏥',
    url: 'http://localhost:3007',
    category: AppCategory.DATABASE,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:9090/health',
    documentation: 'http://localhost:3007',
    tags: ['registry', 'facilities', 'field-ops'],
  },
  {
    id: 'app-pms',
    name: 'Projects Management System',
    description: 'Project lifecycle management with work planning, budgets, risks, and enterprise portfolios',
    icon: '🏗️',
    url: 'http://localhost:3010',
    category: AppCategory.MANAGEMENT,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '2.0.0',
    lastUpdated: new Date('2026-08-07'),
    healthEndpoint: 'http://localhost:8091/health',
    documentation: 'http://localhost:3010',
    tags: ['projects', 'programmes', 'portfolio', 'pms', 'planning'],
  },
  {
    id: 'app-rms',
    name: 'Research Management System',
    description: 'Manage the entire research study lifecycle from idea, proposal, ethics, funding, datasets to publication and knowledge preservation',
    icon: '🔬',
    url: 'http://localhost:3011',
    category: AppCategory.MANAGEMENT,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-07'),
    healthEndpoint: 'http://localhost:8092/health',
    documentation: 'http://localhost:3011',
    tags: ['research', 'studies', 'ethics', 'grants', 'literature', 'datasets', 'publications', 'rms'],
  },
  {
    id: 'app-governance',
    name: 'StatGovernance',
    description: 'Institutional Governance, Compliance, Risk & Internal Control Platform for policies, obligations, controls, and audit assurances',
    icon: '🛡️',
    url: 'http://localhost:3012',
    category: AppCategory.MANAGEMENT,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '8.0.0',
    lastUpdated: new Date('2026-08-14'),
    healthEndpoint: 'http://localhost:8093/health',
    documentation: 'http://localhost:3012',
    tags: ['governance', 'compliance', 'risk', 'controls', 'audits', 'policies', 'statgovernance'],
  },
  {
    id: 'app-spatial',
    name: 'StatSpatial',
    description: 'Interactive geospatial mapping, administrative boundaries, layer registry, and spatial intelligence',
    icon: '🗺️',
    url: 'http://localhost:3014',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-15'),
    healthEndpoint: 'http://localhost:8094/health',
    documentation: 'http://localhost:3014',
    tags: ['spatial', 'gis', 'maps', 'postgis', 'geospatial'],
  },
  {
    id: 'app-knowledge',
    name: 'Public Knowledge Portal',
    description: 'Public portals, open data, publications, digital library and knowledge dissemination — CMS, Open Data Portal, Research Repository, subscriptions and citizen feedback (P17/P40/P41)',
    icon: '📚',
    url: 'http://localhost:8099',
    category: AppCategory.REPORTING,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8099/health',
    documentation: 'http://localhost:8099',
    tags: ['knowledge', 'open-data', 'publications', 'library', 'cms', 'portals'],
  },
  {
    id: 'app-ai-autonomy',
    name: 'AI & Autonomy',
    description: 'Digital twins, predictive analytics, autonomous AI agents, governance guardrails and enterprise knowledge graph (P22/P31/P39)',
    icon: '🧠',
    url: 'http://localhost:8101',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8101/health',
    documentation: 'http://localhost:8101',
    tags: ['ai', 'agents', 'digital-twin', 'knowledge-graph', 'predictions', 'autonomy'],
  },
  {
    id: 'app-learning',
    name: 'Learning, Community & Commercial',
    description: 'LMS, CPD certification, digital badges, CRM, partner portal, billing sync and stakeholder stewardship (P24/P26/P35)',
    icon: '🎓',
    url: 'http://localhost:8102',
    category: AppCategory.MANAGEMENT,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8102/health',
    documentation: 'http://localhost:8102',
    tags: ['learning', 'crm', 'lms', 'certificates', 'partners', 'billing', 'cpid', 'stewardship'],
  },
  {
    id: 'app-geointel',
    name: 'Geospatial & Remote Sensing',
    description: 'GIS layers, spatial analytics, remote sensing & NDVI processing, drone integration, map tiles and geocoding (P44)',
    icon: '🛰️',
    url: 'http://localhost:8103',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8103/health',
    documentation: 'http://localhost:8103',
    tags: ['gis', 'remote-sensing', 'satellite', 'drones', 'spatial', 'geospatial', 'tiles'],
  },
  {
    id: 'app-bpm',
    name: 'Business Process Management',
    description: 'Workflow engine, case management, task management, process mining and automation rules (P48)',
    icon: '⚙️',
    url: 'http://localhost:8104',
    category: AppCategory.MANAGEMENT,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8104/health',
    documentation: 'http://localhost:8104',
    tags: ['bpm', 'workflow', 'process', 'cases', 'tasks', 'automation', 'process-mining'],
  },
  {
    id: 'app-trust',
    name: 'Security, Trust & Identity',
    description: 'SecOps, digital trust, PKI, credentials, provenance and integrity verification (P19/P28)',
    icon: '🔐',
    url: 'http://localhost:8094',
    category: AppCategory.ADMIN,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8094/health',
    documentation: 'http://localhost:8094',
    tags: ['security', 'trust', 'identity', 'pki', 'credentials'],
  },
  {
    id: 'app-ops',
    name: 'Platform Engineering & RunOps',
    description: 'DevOps, observability, SRE, cloud and operations centers (P20/P25/P34/P49)',
    icon: '🛠️',
    url: 'http://localhost:8098',
    category: AppCategory.ADMIN,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8098/health',
    documentation: 'http://localhost:8098',
    tags: ['devops', 'ops', 'observability', 'sre', 'cloud', 'runops'],
  },
  {
    id: 'app-federation',
    name: 'National & Global Federation',
    description: 'National Statistical System, distributed queries, inter-agency collaboration and cross-border federation (P23/P30)',
    icon: '🌐',
    url: 'http://localhost:8105',
    category: AppCategory.INTEGRATION,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8105/health',
    documentation: 'http://localhost:8105',
    tags: ['federation', 'nss', 'statistics', 'cross-border', 'inter-agency'],
  },
  {
    id: 'app-iot',
    name: 'IoT & Mobile Field Ops',
    description: 'IoT gateway, device telemetry, edge sync and mobile field operations (P27/P43)',
    icon: '📡',
    url: 'http://localhost:8106',
    category: AppCategory.INTEGRATION,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8106/health',
    documentation: 'http://localhost:8106',
    tags: ['iot', 'sensors', 'devices', 'telemetry', 'field-ops', 'mobile'],
  },
  {
    id: 'app-data',
    name: 'Data Engineering, Science & Search',
    description: 'Data pipelines, catalog, scientific computing, notebooks and enterprise search (P37/P38/P47)',
    icon: '🗃️',
    url: 'http://localhost:8107',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8107/health',
    documentation: 'http://localhost:8107',
    tags: ['data', 'pipelines', 'catalog', 'science', 'search', 'datops'],
  },
  {
    id: 'app-finance',
    name: 'StatFinance & Grants Hub',
    description: 'Financial management, multi-donor grant accounting, budgets, procurement requisitions, and capital asset registers (Phase 14)',
    icon: '💼',
    url: 'http://localhost:3002/?tab=finance',
    category: AppCategory.MANAGEMENT,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '14.0.0',
    lastUpdated: new Date('2026-08-15'),
    healthEndpoint: 'http://localhost:8096/api/finance/summary',
    documentation: 'http://localhost:3002',
    tags: ['finance', 'grants', 'budgets', 'procurement', 'assets', 'travel'],
  },
  {
    id: 'app-edms',
    name: 'StatGate EDMS & Digital Archives',
    description: 'Enterprise Document Management System, ISO 15489 records repository, digital signatures, and permanent archives (Phase 15)',
    icon: '📁',
    url: 'http://localhost:3002/?tab=edms',
    category: AppCategory.MANAGEMENT,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '15.0.0',
    lastUpdated: new Date('2026-08-15'),
    healthEndpoint: 'http://localhost:8096/api/documents/summary',
    documentation: 'http://localhost:3002',
    tags: ['edms', 'documents', 'archives', 'records', 'signatures', 'policies'],
  },
  {
    id: 'app-integration-hub',
    name: 'StatGate Integration Fabric (EIP)',
    description: 'Enterprise APIs, connectors, webhooks, marketplace plugins, and low-code application delivery (Phases 16, 18 & 42)',
    icon: '🔗',
    url: 'http://localhost:8097',
    category: AppCategory.INTEGRATION,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.MANAGER, UserRole.ADMIN],
    version: '16.0.0',
    lastUpdated: new Date('2026-08-16'),
    healthEndpoint: 'http://localhost:8097/health',
    documentation: 'http://localhost:8097/health',
    tags: ['integration', 'api-gateway', 'connectors', 'webhooks', 'marketplace', 'plugins', 'low-code'],
  },


  {
    id: 'app-helpdesk',
    name: 'Operations Helpdesk',
    description: 'Support ticket management, knowledge base, and operations console',
    icon: '🎫',
    url: 'http://localhost:3005',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:5006/health',
    documentation: 'http://localhost:3005',
    tags: ['helpdesk', 'tickets', 'support'],
  },
  {
    id: 'app-statchat',
    name: 'StatChat',
    description: 'Enterprise collaboration and messaging platform for StatGate',
    icon: '💬',
    url: 'http://localhost:3009',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:4000/health',
    documentation: 'http://localhost:3009',
    tags: ['chat', 'collaboration', 'communication'],
  },
  {
    id: 'app-jupyter',
    name: 'JupyterHub',
    description: 'Multi-user notebook environment for data science and analysis',
    icon: '📓',
    url: 'http://localhost:8000',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8000/hub/api',
    documentation: 'http://localhost:8000',
    tags: ['jupyter', 'notebook', 'python'],
  },
  {
    id: 'app-superset',
    name: 'Superset BI',
    description: 'Business intelligence dashboards and data visualization',
    icon: '📈',
    url: 'http://localhost:8088',
    category: AppCategory.REPORTING,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8088/health',
    documentation: 'http://localhost:8088',
    tags: ['bi', 'dashboards', 'visualization'],
  },
  {
    id: 'app-metabase',
    name: 'Metabase',
    description: 'Lightweight business intelligence and analytics',
    icon: '📊',
    url: 'http://localhost:3001',
    category: AppCategory.REPORTING,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:3001/api/health',
    documentation: 'http://localhost:3001',
    tags: ['bi', 'analytics', 'reports'],
  },
  {
    id: 'app-grafana',
    name: 'Grafana',
    description: 'Monitoring dashboards and observability',
    icon: '📉',
    url: 'http://localhost:3003',
    category: AppCategory.REPORTING,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:3003/api/health',
    documentation: 'http://localhost:3003',
    tags: ['monitoring', 'dashboards', 'observability'],
  },
  {
    id: 'app-prometheus',
    name: 'Prometheus',
    description: 'Metrics collection and alerting',
    icon: '📡',
    url: 'http://localhost:9095',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:9095/-/ready',
    documentation: 'http://localhost:9095',
    tags: ['metrics', 'monitoring', 'alerts'],
  },
  {
    id: 'app-airflow',
    name: 'Airflow',
    description: 'Workflow orchestration and data pipeline scheduling',
    icon: '🔄',
    url: 'http://localhost:8085',
    category: AppCategory.INTEGRATION,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8085/health',
    documentation: 'http://localhost:8085',
    tags: ['orchestration', 'pipelines', 'scheduling'],
  },
  {
    id: 'app-mlflow',
    name: 'MLflow',
    description: 'Machine learning model tracking and experiment management',
    icon: '🤖',
    url: 'http://localhost:5002',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:5002/health',
    documentation: 'http://localhost:5002',
    tags: ['ml', 'models', 'experiments'],
  },
  {
    id: 'app-trino',
    name: 'Trino',
    description: 'Federated SQL query engine across multiple data sources',
    icon: '🔍',
    url: 'http://localhost:8082',
    category: AppCategory.DATABASE,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8082/v1/info',
    documentation: 'http://localhost:8082',
    tags: ['sql', 'federated', 'query'],
  },
  {
    id: 'app-minio',
    name: 'MinIO Storage',
    description: 'Object storage for data assets and artifacts',
    icon: '🗄️',
    url: 'http://localhost:9001',
    category: AppCategory.DATABASE,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:9000/minio/health/ready',
    documentation: 'http://localhost:9001',
    tags: ['storage', 'objects', 's3'],
  },
  {
    id: 'app-mailhog',
    name: 'MailHog',
    description: 'Email testing and preview for development',
    icon: '📧',
    url: 'http://localhost:8025',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8025',
    documentation: 'http://localhost:8025',
    tags: ['email', 'testing', 'dev'],
  },
];

// Application categories
export const APP_CATEGORIES = {
  analytics: {
    label: 'Analytics',
    description: 'Statistical analysis and data exploration',
    color: '#0ea5e9',
  },
  database: {
    label: 'Database',
    description: 'Data storage and retrieval',
    color: '#06b6d4',
  },
  reporting: {
    label: 'Reporting',
    description: 'Report creation and publishing',
    color: '#8b5cf6',
  },
  admin: {
    label: 'Administration',
    description: 'System and user management',
    color: '#ef4444',
  },
  tools: {
    label: 'Tools',
    description: 'Utility and support tools',
    color: '#f59e0b',
  },
  integration: {
    label: 'Integration',
    description: 'External integrations and APIs',
    color: '#10b981',
  },
  management: {
    label: 'Project Management',
    description: 'Portfolio, programme and project lifecycle management',
    color: '#6366f1',
  },
};
