import { User, UserRole, Application, AppStatus, AppCategory } from '@typings/index';

// Mock user data for development
export const MOCK_USER: User = {
  id: 'user-001',
  name: 'John Mwase',
  email: 'john.mwase@statgate.ug',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
  role: UserRole.ADMIN,
  permissions: ['view:all', 'manage:apps', 'admin:access'],
  department: 'Data Analytics',
  lastLogin: new Date(Date.now() - 3600000),
};

// Real applications hosted by the StatGate platform
export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-analytics',
    name: 'StatGate Analytics',
    description: 'Analytical workspace with dataset catalog, notebooks, semantic registry, and executive decision support',
    icon: '📊',
    url: 'http://localhost:5000',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:5000/health',
    documentation: 'http://localhost:5000/',
    tags: ['analytics', 'dashboard', 'notebook'],
  },
  {
    id: 'app-registry',
    name: 'Field Operations Registry',
    description: 'Facility registry with master facility list, organization units, and request workflows',
    icon: '🏥',
    url: 'http://localhost:3000',
    category: AppCategory.DATABASE,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:9090/health',
    documentation: 'http://localhost:3000',
    tags: ['registry', 'facilities', 'field-ops'],
  },
  {
    id: 'app-helpdesk',
    name: 'Operations Helpdesk',
    description: 'Support ticket management, knowledge base, and operations console',
    icon: '🎫',
    url: 'http://localhost:3005',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:5006/health',
    documentation: 'http://localhost:3005',
    tags: ['helpdesk', 'tickets', 'support'],
  },
  {
    id: 'app-statchat',
    name: 'StatChat',
    description: 'Enterprise collaboration and messaging platform for StatGate',
    icon: '💬',
    url: 'http://localhost:5173',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:4000/health',
    documentation: 'http://localhost:5173',
    tags: ['chat', 'collaboration', 'communication'],
  },
  {
    id: 'app-jupyter',
    name: 'JupyterHub',
    description: 'Multi-user notebook environment for data science and analysis',
    icon: '📓',
    url: 'http://localhost:8000',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8000/hub/api',
    documentation: 'http://localhost:8000',
    tags: ['jupyter', 'notebook', 'python'],
  },
  {
    id: 'app-superset',
    name: 'Superset BI',
    description: 'Business intelligence dashboards and data visualization',
    icon: '📈',
    url: 'http://localhost:8088',
    category: AppCategory.REPORTING,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8088/health',
    documentation: 'http://localhost:8088',
    tags: ['bi', 'dashboards', 'visualization'],
  },
  {
    id: 'app-metabase',
    name: 'Metabase',
    description: 'Lightweight business intelligence and analytics',
    icon: '📊',
    url: 'http://localhost:3001',
    category: AppCategory.REPORTING,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.VIEWER, UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:3001/api/health',
    documentation: 'http://localhost:3001',
    tags: ['bi', 'analytics', 'reports'],
  },
  {
    id: 'app-grafana',
    name: 'Grafana',
    description: 'Monitoring dashboards and observability',
    icon: '📉',
    url: 'http://localhost:3003',
    category: AppCategory.REPORTING,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:3003/api/health',
    documentation: 'http://localhost:3003',
    tags: ['monitoring', 'dashboards', 'observability'],
  },
  {
    id: 'app-prometheus',
    name: 'Prometheus',
    description: 'Metrics collection and alerting',
    icon: '📡',
    url: 'http://localhost:9095',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:9095/-/ready',
    documentation: 'http://localhost:9095',
    tags: ['metrics', 'monitoring', 'alerts'],
  },
  {
    id: 'app-airflow',
    name: 'Airflow',
    description: 'Workflow orchestration and data pipeline scheduling',
    icon: '🔄',
    url: 'http://localhost:8085',
    category: AppCategory.INTEGRATION,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8085/health',
    documentation: 'http://localhost:8085',
    tags: ['orchestration', 'pipelines', 'scheduling'],
  },
  {
    id: 'app-mlflow',
    name: 'MLflow',
    description: 'Machine learning model tracking and experiment management',
    icon: '🤖',
    url: 'http://localhost:5002',
    category: AppCategory.ANALYTICS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:5002/health',
    documentation: 'http://localhost:5002',
    tags: ['ml', 'models', 'experiments'],
  },
  {
    id: 'app-trino',
    name: 'Trino',
    description: 'Federated SQL query engine across multiple data sources',
    icon: '🔍',
    url: 'http://localhost:8082',
    category: AppCategory.DATABASE,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8082/v1/info',
    documentation: 'http://localhost:8082',
    tags: ['sql', 'federated', 'query'],
  },
  {
    id: 'app-minio',
    name: 'MinIO Storage',
    description: 'Object storage for data assets and artifacts',
    icon: '🗄️',
    url: 'http://localhost:9001',
    category: AppCategory.DATABASE,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ANALYST, UserRole.MANAGER, UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:9000/minio/health/ready',
    documentation: 'http://localhost:9001',
    tags: ['storage', 'objects', 's3'],
  },
  {
    id: 'app-mailhog',
    name: 'MailHog',
    description: 'Email testing and preview for development',
    icon: '📧',
    url: 'http://localhost:8025',
    category: AppCategory.TOOLS,
    status: AppStatus.OPERATIONAL,
    requiredRoles: [UserRole.ADMIN],
    version: '1.0.0',
    lastUpdated: new Date('2026-07-31'),
    healthEndpoint: 'http://localhost:8025',
    documentation: 'http://localhost:8025',
    tags: ['email', 'testing', 'dev'],
  },
];

// Application categories
export const APP_CATEGORIES = {
  analytics: {
    label: 'Analytics',
    description: 'Statistical analysis and data exploration',
    color: '#0ea5e9',
  },
  database: {
    label: 'Database',
    description: 'Data storage and retrieval',
    color: '#06b6d4',
  },
  reporting: {
    label: 'Reporting',
    description: 'Report creation and publishing',
    color: '#8b5cf6',
  },
  admin: {
    label: 'Administration',
    description: 'System and user management',
    color: '#ef4444',
  },
  tools: {
    label: 'Tools',
    description: 'Utility and support tools',
    color: '#f59e0b',
  },
  integration: {
    label: 'Integration',
    description: 'External integrations and APIs',
    color: '#10b981',
  },
};